name: buuid
description: A uuid library.
version: 0.1.0
# homepage: https://www.example.com
repository: https://github.com/NopeStudio/buuid
issue_tracker: https://github.com/NopeStudio/buuid/issues

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  collection: ^1.15.0
  convert: ^3.0.1
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  tuple: ^2.0.0

dev_dependencies:
  build_runner: ^2.1.11
  hive_generator: ^1.1.3
  json_annotation: ^4.1.0
  test: ^1.17.5