name: buuid
description: A uuid library.
version: 0.1.0
# homepage: https://www.example.com
repository: https://github.com/NopeStudio/buuid
issue_tracker: https://github.com/NopeStudio/buuid/issues

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  collection: ^1.16.0
  convert: ^3.0.1
  tuple: ^2.0.0

dev_dependencies:
  test: ^1.17.5